FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["JwtAuth/JwtAuth.csproj", "JwtAuth/"]
RUN dotnet restore "JwtAuth/JwtAuth.csproj"
COPY . .
WORKDIR "/src/JwtAuth"
RUN dotnet build "JwtAuth.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "JwtAuth.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "JwtAuth.dll"]
